---
# tasks file for docker


- name: Install yum utils
  yum:
    name: yum-utils
    state: latest

- name: Install device-mapper-persistent-data
  yum:
    name: device-mapper-persistent-data
    state: latest

- name: Install lvm2
  yum:
    name: lvm2
    state: latest

- name: Add Docker repo
  get_url:
    url: https://download.docker.com/linux/centos/docker-ce.repo
    dest: /etc/yum.repos.d/docer-ce.repo
  become: yes

- name: Install Docker
  become: yes
  package:
    name: docker-ce
    state: latest
  notify: docker_start

- name: Copy daemon.json
  become: yes
  copy:
    src: daemon.json
    dest: /etc/docker/

- name: Docker version
  become: yes
  shell: docker version --format '{%raw%}{{json .}}{%endraw%}' > /vagrant/docker.fact
  changed_when: no

- name: Copy docker fact
  copy: src=docker.fact dest=/etc/ansible/facts.d
  become: true

- debug: msg='{{ ansible_local }}'


